version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: jobapp_prometheus
    volumes:
      - ./observability/metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    networks:
      - job-portal-network

  grafana:
    image: grafana/grafana:latest
    container_name: jobapp_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - '3000:3000'
    networks:
      - job-portal-network

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jobapp_jaeger
    ports:
      - '16686:16686'
      - '14268:14268'
    networks:
      - job-portal-network

  loki:
    image: grafana/loki:2.7.1
    container_name: jobapp_loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - job-portal-network

  promtail:
    image: grafana/promtail:latest
    container_name: jobapp_promtail
    volumes:
      - ./observability/logs/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - job-portal-network

volumes:
  grafana-data:
  loki-data:

networks:
  job-portal-network:
    external: true
