version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: jobapp_prometheus_local
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: jobapp_grafana_local
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - '3000:3000'

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jobapp_jaeger_local
    ports:
      - '16686:16686'
      - '14268:14268'

  loki:
    image: grafana/loki:2.7.1
    container_name: jobapp_loki_local
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: jobapp_promtail_local
    volumes:
      - ./logs/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/promtail-config.yml

volumes:
  grafana-data:
  loki-data:
